In [1]:
from transformers import AutoTokenizer, AutoModel
import torch

In [5]:
tokenizer = AutoTokenizer.from_pretrained('mrm8488/setfit-distiluse-base-multilingual-cased-v2-finetuned-amazon-reviews-multi-binary')
model = AutoModel.from_pretrained('mrm8488/setfit-distiluse-base-multilingual-cased-v2-finetuned-amazon-reviews-multi-binary')

tokenizer_config.json:   0%|          | 0.00/646 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.92M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

In [6]:
example_sentence = 'its a sunny morning'
example_tokens = tokenizer.encode_plus(example_sentence, max_length = 512, truncation = True, padding = 'max_length', return_tensors = 'pt' )
example_tokens.keys()

dict_keys(['input_ids', 'attention_mask'])

In [8]:
sentences = [
    "It had been sixteen days since the zombies first attacked.",

    "When confronted with a rotary dial phone the teenager was perplexed.",
    "His confidence would have bee admirable if it wasn't for his stupidity.",
    "I'm confused: when people ask me what's up, and I point, they groan.",
    "They called out her name time and again, but were met with nothing but silence.",
    "After the last zombie attack sixteen days back, they are taking control of the city",
]

In [9]:
tokens = {'input_ids': [], 'attention_mask': [] }

for sentence in sentences:
    new_tokens = tokenizer.encode_plus(sentence, max_length = 512, truncation = True, padding = 'max_length', return_tensors = 'pt' )
    tokens['input_ids'].append(new_tokens['input_ids'][0])
    tokens['attention_mask'].append(new_tokens['attention_mask'][0])

# restructure a list of tensors into single tensor
tokens['input_ids'] = torch.stack(tokens['input_ids'])
tokens['attention_mask'] = torch.stack(tokens['attention_mask'])

In [10]:
outputs = model(**tokens)
outputs

BaseModelOutput(last_hidden_state=tensor([[[-1.4130e-01,  1.0888e-01, -3.4584e-03,  ..., -8.9082e-02,
          -3.0747e-02, -7.6690e-02],
         [ 1.6299e-02,  1.9894e-01, -1.0882e-01,  ..., -5.2742e-02,
          -2.0961e-03, -1.4780e-01],
         [ 2.4760e-04,  1.4521e-01, -9.3977e-02,  ..., -7.3673e-02,
           1.7316e-02, -8.8583e-02],
         ...,
         [-1.6017e-02,  9.3510e-02, -7.6549e-02,  ..., -8.2497e-02,
          -1.9845e-02,  3.1521e-02],
         [-3.4594e-02,  7.0730e-02, -8.1687e-02,  ..., -8.1571e-02,
          -3.0237e-02,  2.5746e-02],
         [-2.0701e-02,  8.4218e-02, -6.7711e-02,  ..., -8.5578e-02,
          -3.3836e-02,  2.6451e-02]],

        [[ 6.3952e-02,  6.9482e-02, -5.6794e-02,  ..., -3.3454e-02,
           1.3063e-02, -1.3103e-01],
         [ 9.4216e-02,  7.4013e-02, -6.4895e-02,  ..., -1.0626e-01,
           4.7023e-02, -1.1159e-01],
         [-1.0409e-01,  1.8743e-02, -4.2418e-02,  ..., -5.9116e-03,
          -2.5191e-02, -1.0139e-01],
     

In [11]:
outputs.keys()

odict_keys(['last_hidden_state', 'hidden_states'])

In [12]:
embeddings = outputs.last_hidden_state
embeddings

tensor([[[-1.4130e-01,  1.0888e-01, -3.4584e-03,  ..., -8.9082e-02,
          -3.0747e-02, -7.6690e-02],
         [ 1.6299e-02,  1.9894e-01, -1.0882e-01,  ..., -5.2742e-02,
          -2.0961e-03, -1.4780e-01],
         [ 2.4760e-04,  1.4521e-01, -9.3977e-02,  ..., -7.3673e-02,
           1.7316e-02, -8.8583e-02],
         ...,
         [-1.6017e-02,  9.3510e-02, -7.6549e-02,  ..., -8.2497e-02,
          -1.9845e-02,  3.1521e-02],
         [-3.4594e-02,  7.0730e-02, -8.1687e-02,  ..., -8.1571e-02,
          -3.0237e-02,  2.5746e-02],
         [-2.0701e-02,  8.4218e-02, -6.7711e-02,  ..., -8.5578e-02,
          -3.3836e-02,  2.6451e-02]],

        [[ 6.3952e-02,  6.9482e-02, -5.6794e-02,  ..., -3.3454e-02,
           1.3063e-02, -1.3103e-01],
         [ 9.4216e-02,  7.4013e-02, -6.4895e-02,  ..., -1.0626e-01,
           4.7023e-02, -1.1159e-01],
         [-1.0409e-01,  1.8743e-02, -4.2418e-02,  ..., -5.9116e-03,
          -2.5191e-02, -1.0139e-01],
         ...,
         [ 1.5707e-01,  1

In [13]:
attention_mask = tokens['attention_mask']
attention_mask.shape

torch.Size([6, 512])

In [14]:
resized_attention_mask = attention_mask.unsqueeze(-1).expand(embeddings.size()).float()
resized_attention_mask.shape

torch.Size([6, 512, 768])

In [15]:
resized_attention_mask

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 

In [16]:
resized_attention_mask[0][0].shape

torch.Size([768])

In [17]:
masked_embedding = embeddings * resized_attention_mask
masked_embedding.shape

torch.Size([6, 512, 768])

In [18]:
masked_embedding

tensor([[[-1.4130e-01,  1.0888e-01, -3.4584e-03,  ..., -8.9082e-02,
          -3.0747e-02, -7.6690e-02],
         [ 1.6299e-02,  1.9894e-01, -1.0882e-01,  ..., -5.2742e-02,
          -2.0961e-03, -1.4780e-01],
         [ 2.4760e-04,  1.4521e-01, -9.3977e-02,  ..., -7.3673e-02,
           1.7316e-02, -8.8583e-02],
         ...,
         [-0.0000e+00,  0.0000e+00, -0.0000e+00,  ..., -0.0000e+00,
          -0.0000e+00,  0.0000e+00],
         [-0.0000e+00,  0.0000e+00, -0.0000e+00,  ..., -0.0000e+00,
          -0.0000e+00,  0.0000e+00],
         [-0.0000e+00,  0.0000e+00, -0.0000e+00,  ..., -0.0000e+00,
          -0.0000e+00,  0.0000e+00]],

        [[ 6.3952e-02,  6.9482e-02, -5.6794e-02,  ..., -3.3454e-02,
           1.3063e-02, -1.3103e-01],
         [ 9.4216e-02,  7.4013e-02, -6.4895e-02,  ..., -1.0626e-01,
           4.7023e-02, -1.1159e-01],
         [-1.0409e-01,  1.8743e-02, -4.2418e-02,  ..., -5.9116e-03,
          -2.5191e-02, -1.0139e-01],
         ...,
         [ 0.0000e+00,  0

In [19]:
summed_masked_embeddings = torch.sum(masked_embedding, 1)
summed_masked_embeddings.shape

torch.Size([6, 768])

In [20]:
summed_masked_embeddings

tensor([[-6.5751e-01,  1.4726e+00,  7.1999e-02,  ..., -5.4064e-01,
         -5.4901e-02, -9.3199e-01],
        [ 8.7412e-01,  9.8564e-01, -8.5769e-01,  ..., -5.3035e-01,
          3.6326e-01, -1.7895e+00],
        [ 2.7049e+00,  6.4747e-01, -3.0484e+00,  ..., -4.0741e-01,
         -1.2338e-01, -9.4265e-01],
        [ 8.0345e-01,  1.5752e+00, -2.3580e+00,  ...,  6.2871e-01,
         -7.2746e-01, -3.2476e+00],
        [-8.7456e-01,  8.3709e-01, -2.4331e+00,  ...,  1.6486e+00,
         -1.2733e-03, -2.1928e+00],
        [-1.3467e+00,  1.4697e+00, -5.0702e-01,  ...,  8.4667e-01,
          7.7879e-03, -1.9295e+00]], grad_fn=<SumBackward1>)

In [21]:
resized_attention_mask


tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 

In [22]:
count_of_one_in_mask_tensor = torch.clamp(resized_attention_mask.sum(1), min=1e-9 )

count_of_one_in_mask_tensor.shape

torch.Size([6, 768])

In [23]:
count_of_one_in_mask_tensor


tensor([[14., 14., 14.,  ..., 14., 14., 14.],
        [21., 21., 21.,  ..., 21., 21., 21.],
        [22., 22., 22.,  ..., 22., 22., 22.],
        [24., 24., 24.,  ..., 24., 24., 24.],
        [19., 19., 19.,  ..., 19., 19., 19.],
        [19., 19., 19.,  ..., 19., 19., 19.]])

In [24]:
mean_pooled = summed_masked_embeddings / count_of_one_in_mask_tensor


In [25]:

mean_pooled.shape

torch.Size([6, 768])

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

mean_pooled = mean_pooled.detach().numpy()

cosine_similarity([mean_pooled[0]], mean_pooled[1:] )

array([[0.7456652, 0.5684369, 0.7600504, 0.4877103, 0.8238671]],
      dtype=float32)